[package]
name = "collections"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"
description = "Intrusive singly linked lists, lists, simple queues, tail queues and a red-black tree"
repository.workspace = true
publish = false

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "shapes"
harness = false

[[bench]]
name = "rb_tree"
harness = false

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unfulfilled_lint_expectations = "deny"
missing_docs = "deny"
elided_lifetimes_in_paths = "deny"
unused_qualifications = "deny"
trivial_numeric_casts = "deny"
non_ascii_idents = "deny"
meta_variable_misuse = "deny"
let_underscore_drop = "deny"
macro_use_extern_crate = "deny"
missing_debug_implementations = "deny"
missing_copy_implementations = "deny"
unreachable_pub = "deny"
single_use_lifetimes = "deny"
unused_lifetimes = "deny"
trivial_casts = "deny"
unused_results = "deny"
unused_import_braces = "deny"
explicit_outlives_requirements = "deny"
redundant_lifetimes = "deny"
unit_bindings = "deny"
unnameable_types = "deny"
variant_size_differences = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
restriction = { level = "deny", priority = -1 }
blanket_clippy_restriction_lints = "allow"
implicit_return = "allow"
semicolon_inside_block = "allow"
mod_module_files = "allow"
missing_trait_methods = "allow"
arbitrary_source_item_ordering = "allow"
question_mark_used = "allow"
pub_use = "allow"
single_call_fn = "allow"
inline_modules = "allow"
undocumented_unsafe_blocks = "allow"
multiple_unsafe_ops_per_block = "allow"
missing_docs_in_private_items = "allow"
redundant_pub_crate = "allow"
pub_with_shorthand = "allow"
