[package]
name = "kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A work-in-progress Mach microkernel implementation in Rust"
repository.workspace = true
publish = false

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
clock = { path = "../clock" }
collections.workspace = true
elf-load = { path = "../elf-load" }
kmem.workspace = true
lock.workspace = true
mach-mig-sys = { path = "../mach-mig-sys" }

[lints]
workspace = true
