[package]
name = "clock"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"
description = "The machine clock and Scheme 6 hashed timer wheels"
repository.workspace = true
publish = false

[dependencies]
collections.workspace = true
lock.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "timers"
harness = false

[lints]
workspace = true
